### ISSUE TITLE
Game - Version 50

### ISSUE THREAD

**Issue by newerton** [newerton/bombcrypto-bot#174]
Settings for version 50
--
Configurações para a versão 50

v2.0.4 - Correção das imagens de stamina.
v2.0.5 - Correção do envio de heróis para a casa
v2.0.6 - Adicionado o modo do jogo por contas

config.yaml

```yaml
threshold:
  work_button: 0.95
  home_enable_button: 0.95
  heroes_green_bar: 0.95
  heroes_red_bar: 0.98
  heroes_full_bar: 0.8

offsets:
  work_button_green: [160, 190]
  work_button_full: [90, 120]
  house_button: [280, 310]
```

Obs
--
- Se o bot não detectar os botões, ajustar o threshold para baixo.
- If the bot does not detect the buttons, adjust the threshold lower.
