### ISSUE TITLE
Game - Version 57

### ISSUE THREAD

**Issue by newerton** [newerton/bombcrypto-bot#215]
Settings for version 57
--
Configurações para a versão 57

v2.1.0 - Correção das imagens de stamina, botão WORK e botões ALL.
v2.1.0 - Envio de heróis pela cor do diamante, "AJUSTAR O THRESOLHD"

config.yaml

```yaml
threshold:
  heroes_full_bar: 0.9
  heroes_red_bar: 0.9
  heroes:
    common: 0.8
    rare: 0.8
    super_rare: 0.8
    epic: 0.8
    legend: 0.8
    super_legend: 0.8

offsets:
  work_button_green: [200, 230]
  work_button_full: [140, 170]
  house_button: [340, 370]
```

Obs
--
- Se o bot não detectar os botões, ajustar o threshold para baixo.
- If the bot does not detect the buttons, adjust the threshold lower.
--
- **As raridades do heróis da lista, agora são gemas, não é mais os labels. Terei que buscar todas as gemas das raridades, eu tenho a gema de comum, raro, super raro, epic e lendário. Para quem tiver uma conta com CASA e Super lendário, e puder me passar o usuário e senha. Por que a funcionalidade da casa não está funcionando até uma nova versão do BOT.**
- **The rarities of the heroes in the list are now gems, not labels anymore. I will have to get all the rarities gems, I have the common, rare, super rare, epic and legendary gem. For those who have an account with CASA and Super Legendary, and can give me the username and password. Why the home functionality is not working until a new version of the BOT.**
