### ISSUE TITLE
feature: Launch heroes separately by groups

### ISSUE THREAD

**Issue by Kfilal** [newerton/bombcrypto-bot#57]
Hello,
 is there a way to launch epic on green and commons on full ?

**Comment by newerton** [comment]
@Kfilal Hello!

Adding as a new feature!

Maybe I do it this way:

```
heroes:
    mode: 'groups'
    groups:
        green_bars: ['super_rare', 'epic', 'legend', 'super_legend']
        full_bars: ['common', 'rare']
```
